# Global users - all instances
variable "admin_user_name" {
  description = "Administrator user name"
  type        = string
}

variable "readonly_user_name" {
  description = "Readonly user name"
  type        = string
}

# <change me>
# Passwords DB Instances
#
# Every DB instance requires unique admin_user_pass, readonly_user_pass
# and db_user_passes which is a list of N number of passwords (default is 3 users)
# for the N number of new databases (default is 3 DBs) to be created per instance 
#
# If you need to add new DB, copy whole block of the 3 must have variables and adjust
# their names. For example for sixth instance 
# admin_user_pass_1 becomes admin_user_pass_6
# readonly_user_pass_1 becomes readonly_user_pass_6
# db_user_passes_1 becomes db_user_passes_6
# 
# These passwords are auto generated by ./script_pass.sh so don't forget to alter that script too

## First DB instance
### Admin user pass
variable "admin_user_pass_1" {
  description = "Admin pass for instance 1"
  type        = string
  sensitive   = true
}

### Read-Only user pass
variable "readonly_user_pass_1" {
  description = "Readonly user password for instance 1"
  type        = string
  sensitive   = true
}

### DB users Passwords 
variable "db_user_passes_1" {
  description = "DB users passwords for instance 1"
  type      = list(string)
  sensitive = true
}

## Second DB instance
### Admin user pass
variable "admin_user_pass_2" {
  description = "Admin pass for instance 2"
  type        = string
  sensitive   = true
}

### Read-Only user pass
variable "readonly_user_pass_2" {
  description = "Readonly user password for instance 2"
  type        = string
  sensitive   = true
}

### DB users Passwords 
variable "db_user_passes_2" {
  description = "DB users passwords for instance 2"
  type      = list(string)
  sensitive = true
}

## Third DB instance
### Admin user pass
variable "admin_user_pass_3" {
  description = "Admin pass for instance 3"
  type        = string
  sensitive   = true
}

### Read-Only user pass
variable "readonly_user_pass_3" {
  description = "Readonly user password for instance 3"
  type        = string
  sensitive   = true
}

### DB users Passwords 
variable "db_user_passes_3" {
  description = "DB users passwords for instance 3"
  type      = list(string)
  sensitive = true
}

## Fourth DB instance
### Admin user pass
variable "admin_user_pass_4" {
  description = "Admin pass for instance 4"
  type        = string
  sensitive   = true
}

### Read-Only user pass
variable "readonly_user_pass_4" {
  description = "Readonly user password for instance 4"
  type        = string
  sensitive   = true
}

### DB users Passwords 
variable "db_user_passes_4" {
  description = "DB users passwords for instance 4"
  type      = list(string)
  sensitive = true
}

## Fifth DB instance
### Admin user pass
variable "admin_user_pass_5" {
  description = "Admin pass for instance 5"
  type        = string
  sensitive   = true
}

### Read-Only user pass
variable "readonly_user_pass_5" {
  description = "Readonly user password for instance 5"
  type        = string
  sensitive   = true
}

### DB users Passwords 
variable "db_user_passes_5" {
  description = "DB users passwords for instance 5"
  type      = list(string)
  sensitive = true
}
